version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  server:
    container_name: server
    build:
      context: ./api/
      target: dev
      args:
        - NODE_ENV=development
        - PORT=8000
    
    env_file:
      - ./api/.env.development.local
    
    ports:
      - "8000:8000"
      - "9229:9229"
      - "9230:9230"
      - "9100:9100"
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    
    restart: 'always'
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      
    healthcheck:
      disable: true

  mongo:
    container_name: mongo
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    ports:
      - 27018:27017
    logging:
      driver: "none"
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

    volumes:
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh/:ro
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/ --quiet` ] && echo 0 || echo 1"


  proxy:

    container_name: proxy
    ports:
      - '80:80'
    build:
      context: ./nginx/

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: 'always'

    depends_on:
      - server
      # - client

# volumes:
#   notused: